### ISSUE TITLE
Issues running Corb via AppServicesPort

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/corb2#143]
I am using CorbTask, but logging seems to indicate all settings are passed through correctly. I see checks for the right modules database and all, but when it tries to invoke uri or transform module, it fails with the message that it cannot find it.

gradle task:

```
ext {
    // XCC URL for running corb task below
    contentXccUrl = "xcc://${mlUsername}:${mlPassword}@${mlHost}:${mlAppServicesPort}/${mlContentDatabaseName}"
}

task migrateAlerts(type: com.marklogic.gradle.task.CorbTask, dependsOn: ['mlLoadModules']) {
    xccConnectionUri = contentXccUrl
    modulesDatabase = "cluey-app-modules"
    moduleRoot = "/"
    urisModule = "/corb/migrateAlertsUris.sjs"
    processModule = "/corb/migrateAlertsTransform.sjs"
}
```

console output:

```
> Task :migrateAlerts FAILED
Task ':migrateAlerts' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java''. Working directory: /Users/gjosten/Projects/github-ss/cluey-backend Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java -DMODULES-DATABASE=cluey-app-modules -DPROCESS-MODULE=corb/migrateAlertsTransform.sjs -DURIS-MODULE=corb/migrateAlertsUris.sjs -DXCC-CONNECTION-URI=xcc://admin:dc6530d9046f5626614486df0f5a6be3@localhost:8700/cluey-app-content -Dawt.toolkit=sun.lwawt.macosx.LWCToolkit -Dfile.encoding.pkg=sun.io -Dfile.separator=/ -DgopherProxySet=false -Djava.awt.graphicsenv=sun.awt.CGraphicsEnvironment -Djava.awt.printerjob=sun.lwawt.macosx.CPrinterJob -Djava.class.path=/Users/gjosten/.gradle/wrapper/dists/gradle-5.2.1-bin/9lc4nzslqh3ep7ml2tp68fk8s/gradle-5.2.1/lib/gradle-launcher-5.2.1.jar -Djava.class.version=52.0 -Djava.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/endorsed -Djava.ext.dirs=/Users/gjosten/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java -Djava.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre -Djava.library.path=/Users/gjosten/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:. -Djava.runtime.name=Java(TM) SE Runtime Environment -Djava.runtime.version=1.8.0_162-b12 -Djava.specification.name=Java Platform API Specification -Djava.specification.vendor=Oracle Corporation -Djava.specification.version=1.8 -Djava.vendor=Oracle Corporation -Djava.vendor.url=http://java.oracle.com/ -Djava.vendor.url.bug=http://bugreport.sun.com/bugreport/ -Djava.version=1.8.0_162 -Djava.vm.info=mixed mode -Djava.vm.name=Java HotSpot(TM) 64-Bit Server VM -Djava.vm.specification.name=Java Virtual Machine Specification -Djava.vm.specification.vendor=Oracle Corporation -Djava.vm.specification.version=1.8 -Djava.vm.vendor=Oracle Corporation -Djava.vm.version=25.162-b12 -Dlibrary.jansi.path=/Users/gjosten/.gradle/native/jansi/1.17.1/osx -Dline.separator=
 -Dorg.gradle.appname=gradlew -Dos.arch=x86_64 -Dos.name=Mac OS X -Dos.version=10.13.6 -Dpath.separator=: -Dsun.arch.data.model=64 -Dsun.boot.class.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/classes -Dsun.boot.library.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib -Dsun.cpu.endian=little -Dsun.cpu.isalist -Dsun.io.unicode.encoding=UnicodeBig -Dsun.java.command=org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.2.1 -Dsun.java.launcher=SUN_STANDARD -Dsun.jnu.encoding=UTF-8 -Dsun.management.compiler=HotSpot 64-Bit Tiered Compilers -Dsun.os.patch.level=unknown -Duser.dir=/Users/gjosten/Projects/github-ss/cluey-backend -Duser.home=/Users/gjosten -Duser.name=gjosten -Duser.timezone -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/var/folders/35/frcvchb956g5k50xr5kvg_5ccnv1ld/T/ -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/gjosten/.gradle/caches/modules-2/files-2.1/com.marklogic/marklogic-corb/2.5.0/6515f72c6ee9f9b367f5f976ff01d11f9a7f1e42/marklogic-corb-2.5.0.jar:/Users/gjosten/.gradle/caches/modules-2/files-2.1/com.marklogic/marklogic-xcc/10.0.5/b7cef07dc074bc12b86b02960f620cd1defe039e/marklogic-xcc-10.0.5.jar:/Users/gjosten/.gradle/caches/modules-2/files-2.1/org.webjars/angularjs/1.7.9/dde587595f111efb319486fbd1d0709946578555/angularjs-1.7.9.jar:/Users/gjosten/.gradle/caches/modules-2/files-2.1/org.webjars/bootstrap/3.4.1/2c6a8508a4f1484abcaf334cf2fe3df97cf93eac/bootstrap-3.4.1.jar:/Users/gjosten/.gradle/caches/modules-2/files-2.1/org.webjars/jquery/3.4.1/f9cd2ff7f2da4c3f6839e9d5e5e92b0bbe1cbfb/jquery-3.4.1.jar:/Users/gjosten/.gradle/caches/modules-2/files-2.1/com.google.code.externalsortinginjava/externalsortinginjava/0.6.0/cf55d839cef1c5148b337e4d5d8d6f75204a4f72/externalsortinginjava-0.6.0.jar:/Users/gjosten/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-csv/1.4/fc2512d2109144df353501266ac4bbe179058afd/commons-csv-1.4.jar com.marklogic.developer.corb.Manager
Successfully started process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java''
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.AbstractManager logRuntimeArgs
INFO: runtime arguments = -DMODULES-DATABASE=cluey-app-modules -DPROCESS-MODULE=corb/migrateAlertsTransform.sjs -DURIS-MODULE=corb/migrateAlertsUris.sjs -Dawt.toolkit=sun.lwawt.macosx.LWCToolkit -Dfile.encoding.pkg=sun.io -Dfile.separator=/ -DgopherProxySet=false -Djava.awt.graphicsenv=sun.awt.CGraphicsEnvironment -Djava.awt.printerjob=sun.lwawt.macosx.CPrinterJob -Djava.class.version=52.0 -Djava.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/endorsed -Djava.ext.dirs=/Users/gjosten/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java -Djava.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre -Djava.library.path=/Users/gjosten/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:. -Djava.runtime.name=Java(TM) SE Runtime Environment -Djava.runtime.version=1.8.0_162-b12 -Djava.specification.name=Java Platform API Specification -Djava.specification.vendor=Oracle Corporation -Djava.specification.version=1.8 -Djava.vendor=Oracle Corporation -Djava.vendor.url=http://java.oracle.com/ -Djava.vendor.url.bug=http://bugreport.sun.com/bugreport/ -Djava.version=1.8.0_162 -Djava.vm.info=mixed mode -Djava.vm.name=Java HotSpot(TM) 64-Bit Server VM -Djava.vm.specification.name=Java Virtual Machine Specification -Djava.vm.specification.vendor=Oracle Corporation -Djava.vm.specification.version=1.8 -Djava.vm.vendor=Oracle Corporation -Djava.vm.version=25.162-b12 -Dlibrary.jansi.path=/Users/gjosten/.gradle/native/jansi/1.17.1/osx -Dline.separator=
 -Dorg.gradle.appname=gradlew -Dos.arch=x86_64 -Dos.name=Mac OS X -Dos.version=10.13.6 -Dpath.separator=: -Dsun.arch.data.model=64 -Dsun.boot.class.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/classes -Dsun.boot.library.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib -Dsun.cpu.endian=little -Dsun.cpu.isalist -Dsun.io.unicode.encoding=UnicodeBig -Dsun.jnu.encoding=UTF-8 -Dsun.management.compiler=HotSpot 64-Bit Tiered Compilers -Dsun.os.patch.level=unknown -Duser.dir=/Users/gjosten/Projects/github-ss/cluey-backend -Duser.home=/Users/gjosten -Duser.name=gjosten -Duser.timezone -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/var/folders/35/frcvchb956g5k50xr5kvg_5ccnv1ld/T/ -Duser.country=US -Duser.language=en -Duser.variant
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.AbstractManager initProperties
INFO: applying system property: MODULES-DATABASE to properties
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.AbstractManager initProperties
INFO: applying system property: PROCESS-MODULE to properties
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.AbstractManager initProperties
INFO: applying system property: URIS-MODULE to properties
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.AbstractManager initProperties
INFO: applying system property: XCC-CONNECTION-URI to properties
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.AbstractManager initSSLConfig
INFO: Using TrustAnyoneSSSLConfig because no SSL-CONFIG-CLASS value specified.
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.AbstractManager initContentSourcePool
INFO: Using the content source manager com.marklogic.developer.corb.DefaultContentSourcePool
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.DefaultContentSourcePool init
INFO: Using the connection policy ROUND-ROBIN
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.DefaultContentSourcePool initContentSource
INFO: Initialized ContentSource user=admin, cb=cluey-app-content [provider: address=localhost/127.0.0.1:8700, pool=0/64]
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured modules db: cluey-app-modules
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured modules xdbc root: /
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured modules root: /
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured uri module: corb/migrateAlertsUris.sjs
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured uri file: null
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured uri loader: null
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured process module: corb/migrateAlertsTransform.sjs
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured process task: null
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured pre batch module: null
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured pre batch task: null
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured post batch module: null
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured post batch task: null
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured init module: null
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured init task: null
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured thread count: 1
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured batch size: 1
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured failonError: true
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured URIs queue max in-memory size: 1,000
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager logOptions
INFO: Configured URIs queue temp dir: null
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.AbstractManager logProperties
INFO: Loaded property URIS-MODULE=corb/migrateAlertsUris.sjs
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.AbstractManager logProperties
INFO: Loaded property MODULES-DATABASE=cluey-app-modules
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.AbstractManager logProperties
INFO: Loaded property PROCESS-MODULE=corb/migrateAlertsTransform.sjs
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager prepareModules
INFO: checking modules, database: cluey-app-modules
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager insertModule
INFO: Skipping module installation: corb/migrateAlertsUris.sjs
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager insertModule
INFO: Skipping module installation: corb/migrateAlertsTransform.sjs
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager run
INFO: com.marklogic.developer.corb.Manager starting: version 2.5.0 on 1.8.0_162 (Java(TM) SE Runtime Environment)
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager run
INFO: maximum heap size = 3,641 MiB
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager populateQueue
INFO: populating queue
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.QueryUrisLoader open
INFO: buffer size = 0, caching = false
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.QueryUrisLoader open
INFO: Invoking URIS-MODULE /corb/migrateAlertsUris.sjs
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.QueryUrisLoader closeRequestAndSession
INFO: closing uris session
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager stop
INFO: cleaning up
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager stop
INFO: Shutting down the thread pool
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager run
SEVERE: While invoking URIS-MODULE
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager stop
INFO: cleaning up
Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager main
SEVERE: Error while running CoRB
com.marklogic.developer.corb.CorbException: While invoking URIS-MODULE
        at com.marklogic.developer.corb.QueryUrisLoader.open(QueryUrisLoader.java:125)
        at com.marklogic.developer.corb.Manager.runUrisLoader(Manager.java:814)
        at com.marklogic.developer.corb.Manager.populateQueue(Manager.java:835)
        at com.marklogic.developer.corb.Manager.run(Manager.java:583)
        at com.marklogic.developer.corb.Manager.main(Manager.java:138)
Caused by: com.marklogic.xcc.exceptions.XQueryException: XDMP-MODNOTFOUND: Module /corb/migrateAlertsUris.sjs not found
 [Session: user=admin, cb=cluey-app-content [ContentSource: user=admin, cb=cluey-app-content [provider: address=localhost/127.0.0.1:8700, pool=1/64]]]
 [Client: XCC/10.0-5, Server: XDBC/10.0-4]
in /corb/migrateAlertsUris.sjs
        at com.marklogic.xcc.impl.handlers.ServerExceptionHandler.handleResponse(ServerExceptionHandler.java:34)
        at com.marklogic.xcc.impl.handlers.EvalRequestController.serverDialog(EvalRequestController.java:99)
        at com.marklogic.xcc.impl.handlers.AbstractRequestController.runRequest(AbstractRequestController.java:92)
        at com.marklogic.xcc.impl.SessionImpl.submitRequestInternal(SessionImpl.java:495)
        at com.marklogic.xcc.impl.SessionImpl.submitRequest(SessionImpl.java:490)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.marklogic.developer.corb.DefaultContentSourcePool$SessionInvocationHandler.invoke(DefaultContentSourcePool.java:393)
        at com.sun.proxy.$Proxy1.submitRequest(Unknown Source)
        at com.marklogic.developer.corb.QueryUrisLoader.open(QueryUrisLoader.java:118)
        ... 4 more

Oct 17, 2020 12:44:20 PM com.marklogic.developer.corb.Manager main
INFO: unexpected error - exiting with code 2
:migrateAlerts (Thread[Execution worker for ':',5,main]) completed. Took 0.658 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':migrateAlerts'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by grtjn** [comment]
Forgot to add: if I deploy the modules to the Modules database, it runs fine with exact same settings... :-/

**Comment by hansenmc** [comment]
If you don’t want to have to deploy the modules that you are executing, then append
    |ADHOC 
to the module paths
https://github.com/marklogic-community/corb2#adhoc-modules

Or apply the INSTALL option
    INSTALL=true
https://github.com/marklogic-community/corb2#INSTALL

**Comment by grtjn** [comment]
Unfortunately, adhoc is not an option, since I am importing a library from the transform code, which cannot be found either if it is running with wrong modules database. Same applies to the install option I suspect.

**Comment by grtjn** [comment]
I resorted to using adhoc in combination with a transform module that uses invokefunction to enforce the correct modules database. I would welcome bringing back this feature, it would increase Corb's flexibility.

**Comment by hansenmc** [comment]
I think the confusion/issue is that most people would assume that `MODULES-DATABASE` would indicate the name of the modules database in which to find the specified module, similar to how `XCC-DBNAME` works. However, XCC doesn't allow you to control which modules database is used. You use whichever modules DB is configured for the appserver you are executing against.

`MODULES-DATABASE` is used in conjunction with `INSTALL=true` to indicate which (modules) database you want to insert modules into. 
https://github.com/marklogic-community/corb2/blob/master/src/main/java/com/marklogic/developer/corb/Manager.java#L693

However, that still only works if the `MODULES-DATABASE` specified is the modules database for the appserver executing against. I don't believe that the XCC API provides a way to obtain the name of the modules database, but we could eval() some code to obtain it, and then allow you to insert the module into the modules DB without having to specify the name of the modules database in `MODULES-DATABASE`...
