### ISSUE TITLE
When i ran CORB in my windows machine it is throwing ERROR ?

### ISSUE THREAD

**Issue by Yaswanth-C** [marklogic-community/corb2#82]
I tried running sample corb example by following this [documentation][1] . I am having MarkLogic 9 in my machine and for that i had downloaded following jars `marklogic-corb-2.4.0.jar`,`marklogic-xcc-9.0.4` . And created selector.xqy and transform.xqy files as specified in documentaion and kept all these in corb folder.When i tried running it , it is showing Error like below

   

    D:\ChromeDownloads\corb\corb>java -cp "marklogic-corb-2.4.0.jar;marklogic-xcc-9.
    0.4" -DOPTIONS-FILE=my.properties com.marklogic.developer.corb.Manager xcc://adm
    in:admin@localhost:9000/CSV-DB
    Error: A JNI error has occurred, please check your installation and try again
    Exception in thread "main" java.lang.NoClassDefFoundError: com/marklogic/xcc/exc
    eptions/RequestException
            at java.lang.Class.getDeclaredMethods0(Native Method)
            at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
            at java.lang.Class.privateGetMethodRecursive(Unknown Source)
            at java.lang.Class.getMethod0(Unknown Source)
            at java.lang.Class.getMethod(Unknown Source)
            at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
            at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
    Caused by: java.lang.ClassNotFoundException: com.marklogic.xcc.exceptions.Reques
    tException
            at java.net.URLClassLoader.findClass(Unknown Source)
            at java.lang.ClassLoader.loadClass(Unknown Source)
            at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
            at java.lang.ClassLoader.loadClass(Unknown Source)
            ... 7 more

Is there any other configuration changes need to be done to run CORB ?

**NOTE**: Here i had used file separator `;` , when i used `:` it is saying `Error: Could not find or load main class com.marklogic.developer.corb.Manager`

  [1]: https://github.com/marklogic-community/corb2/wiki/Hello-World-from-CORB

**Comment by bbandlamudi** [comment]
Could you check your classpath? I am wondering if it needs to be marklogic-xcc-9.0.4.jar and not marklogic-xcc-9.0.4. On windows systems you will need to use ';' and not ':'.

**Comment by hansenmc** [comment]
[As answered in the stackoverflow question](https://stackoverflow.com/a/48613211/14419), the XCC jar isn't being loaded, so the XCC classes are not found. 

You need to add the `.jar` file extension to the XCC jar in your classpath.

    java -cp "marklogic-corb-2.4.0.jar;marklogic-xcc-9.0.4.jar"

**Comment by Yaswanth-C** [comment]
I am very sorry

**Comment by Yaswanth-C** [comment]
I am very sorry @bbandlamudi & @hansenmc . Seriously i don't know how i forgot that simple one .
